version: '3.3'
services:
  vuejs:
    build:
      context: ./front/
    restart: always
    ports: 
      - "8081:8080"
    volumes: 
      - "./front/:/app/"
    networks: 
      - "ensiie"
      
  node:
    build:
      context: ./back/
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - ./back/:/app
    - ./back/error.log:/usr/src/app/error.log
    links:
      - postgres
    networks:
      - "ensiie"

  postgres:
    build:
      context: ./back/.docker/postgres/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./back/postgres-data:/var/lib/postgresql/data
      - ./back:/var/www/html
    working_dir: /var/www/html
    networks:
      - "ensiie"

networks:
    ensiie:
        driver: bridge
